'use strict';

var mongoose = require('mongoose');
var SoUser = mongoose.model('SoUser');
var Answer = mongoose.model('Answer');

var request = require('request');


//TODO: Refactor this class to have a common class with issue or anything that
// depends on the git api.
module.exports = function (BaseFrame){
    return {
        /** Looks for the given (req.params) repository in the database.
        *
        * @param req - Express request
        * @param res - Express response
        */
        find: function (req, res){
            var repo = {repositories: req.params.projectId};

            SoUser.find(repo, 'soId _id', {sort: '-soId -updatedAt'}, function(err, users){
                res.send(users);
            });
        },

        /** Stores in the database all the users from the given repository.
        *
        * @param req - Express request
        * @param res - Express response
        */
        populate: function(req, res){
            var repo = req.params;

            var options = {
                headers: {
                    'User-Agent': 'software-expertise',
                    Accept: 'application/vnd.github.v3+json'
                },
                url: 'https://api.github.com/repositories/' +
                  repo.projectId + '/contributors?per_page=100'
            };
            request(options, callback);

            /** Callback to the request. This will create the users and save
            * them in the database.
            *
            * @param error - Any errors ocurred during the http request
            * @param response - The response from the other server
            * @param body - The response body (string). Final html or JSON.
            */
            function callback(error, response, body){
                if (!error && response.statusCode == 200) {
                    var users = [];
                    var results = JSON.parse(body);

                    for (var i in results) {
                        var result = results[i];
                        var user = {
                            gitHubId: result.id,
                            $addToSet: {repositories: repo.projectId}
                        };

                        SoUser.update({_id: result.login}, user, {upsert: true}, function(err){
                            if(err){
                                console.log(err.message);
                            }else{
                                console.log('User saved successfully!');
                            }
                        });
                    }
                } else {
                    console.log(error);
                    console.log(body);
                    res.sendStatus(500);
                }
                nextRequest(response.headers.link);
            }

            /** This reads and parses the link header in GitHub API to get the
            * next url and avoid infinite loop (next of the last page
            * is the first one)
            *
            * @param link - Value of headers['link'] from the response
            */
            function nextRequest(link){
                if(link){
                    //The first entry of the links array is the next page
                    var next = link.split(', ')[0];
                    //This should be always 0, but just to make sure, will get the indexOf
                    var begin = next.indexOf('<');
                    var end = next.indexOf('>');

                    //This gets string = [begin, end)
                    var new_url = next.substring(begin + 1, end);

                    var lastEqualsIndex = new_url.lastIndexOf('=');
                    var nextPage = new_url.slice(lastEqualsIndex + 1, next.length);
                    console.log(nextPage);
                    if(nextPage != 1){
                        options.url = new_url;
                        request(options, callback);
                    }
                }
            }
        },

        populateUserTags: function (req, res){
            /** Filter is generated by stackexchange api. This one includes
            * count, has_synonyms, name, synonyms. Page and total are added to
            * .wrapper fields.
            * To understand better how this works, check
            *https://api.stackexchange.com/docs/tags-on-users#pagesize=100&order=desc&sort=popular&ids=696885&filter=!)sCN9OzMlifJVZJ50hGQ&site=stackoverflow
            */
            var soId = req.params.soId;
            var url = 'https://api.stackexchange.com/2.2/users/' + soId +
                '/tags?pagesize=100&order=desc&sort=popular&site=stackoverflow&filter=!)sCN9OzMlifJVZJ50hGQ&page=';

            var options = {
                headers: {
                    'Accept-Encoding': 'gzip'
                },
                gzip: true,
                url: url
            };

            request(options, function (error, response, body){
                if (!error && response.statusCode == 200) {
                    var results = JSON.parse(body);
                    var tags = [];
                    for(var i in results.items){
                        var result = results.items[i];
                        var teste = {
                            _id: result.name,
                            count: result.count
                        };
                        tags.push(teste);
                    }
                    res.send(tags);
                    SoUser.update({soId: soId}, {$addToSet: {tags: {$each: tags}}}, {upsert: true}, function(err){
                        if(err){
                            console.log(err.message);
                        }else{
                            console.log('User saved successfully!');
                        }
                    });
                } else {
                    console.log("Error");
                    console.log(error, body);
                    res.sendStatus(500);
                }
            });
        },

        populateUserAnswers: function(req, res){
            var soId = req.params.soId;
            /* To know more about this check
            * https://api.stackexchange.com/docs/answers-on-users#pagesize=100&order=desc&sort=activity&ids=696885&filter=!t)IWIB_jIM*PQgVlKVx*bpK7iv9Avm9&site=stackoverflow
            */
            var url = 'https://api.stackexchange.com/2.2/users/' + soId +
                '/answers?pagesize=100&order=desc&sort=activity&site=stackoverflow&filter=!t)IWIB_jIM*PQgVlKVx*bpK7iv9Avm9&page=';

            var options = {
                headers: {
                    'Accept-Encoding': 'gzip'
                },
                gzip: true,
                url: url
            };
        },

        tags: function (req, res) {
            SoUser.findOne(req.params, function(err, user){
                if(err){
                    console.log(err);
                    res.send(err);
                }else{
                    res.send(user.tags)
                }
            });
        }
    }
}
